### ISSUE TITLE
update manatee county parks and rec link

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/robinson-sport-fish#8]
https://github.com/tbep-tech/robinson-sport-fish/blob/e836fc5746dd9eca59a80c44b80d7ee34d658c57/index.qmd#L161

Per Alissa Powers (alissa.powers@mymanatee.org) -- "I was enjoying the latest TBEP newsletter and was just about to share the link to the Robinson Preserve Sportfish Tagging Project (https://tbep-tech.github.io/robinson-sport-fish/ ) to our communications team when I noticed that the Manatee County Parks and Natural Resources link goes to our Sports and Leisure Department. Is there anyway you can fix the link to go to the Natural Resources Department (https://www.mymanatee.org/departments/natural_resources )? The departments were split about 18 months ago."

**Comment by esherwoo77** [comment]
Updated the links on front page and About pages. Waiting for it to be pushed to the live website.

**Comment by fawda123** [comment]
Looks like @jonpeake is building the site locally.  The changes won't occur on the web page until this is done (i.e., the edited .qmd files won't be reflected in the .html files in the docs folder).  I tried doing this on my end but it looks like the data.qmd file is reading an external file not in the repo (params.RData).  Consider adding this file and setting up an automatic site build through [GitHub Actions](https://github.com/quarto-dev/quarto-actions) when changes are made in the repo.

**Comment by jonpeake** [comment]
> Looks like @jonpeake is building the site locally. The changes won't occur on the web page until this is done (i.e., the edited .qmd files won't be reflected in the .html files in the docs folder). I tried doing this on my end but it looks like the data.qmd file is reading an external file not in the repo (params.RData). Consider adding this file and setting up an automatic site build through [GitHub Actions](https://github.com/quarto-dev/quarto-actions) when changes are made in the repo.

Unfortunately we are not able to set this up at this time due to sensitive information contained within that params.RData file. The site needs to access our databases hosted on our server, and that file contains the information needed to connect to the databases. We thought it wise to avoid any potential security issues by leaving it out of the GitHub page. Once the project is finished and we have all data in hand, we should be able to upload all data directly to GitHub and have the website render directly from the .qmd files using GitHub Actions. Until then though, local rendering appears to be the best way to avoid compromising the security of our data.

**Comment by jonpeake** [comment]
I was able to fix the links on my end, so we should be good to go. I also updated the code to better render the logos (the Manatee County logo was a bit squished in the previous version).
